/* ToolPilot canonical dataset — shared by index (app.js) and admin (admin.js).
   Admin edits never touch this file; they live in localStorage overlays
   (tp_tool_overrides / tp_deletes / tp_custom / tp_cats_full). */
window.TP_DATA = {
categories: [
  { id:"chat", name:"Chat & Assistants", emoji:"💬" },
  { id:"writing", name:"Writing & SEO", emoji:"✍️" },
  { id:"image", name:"Image & Art", emoji:"🎨" },
  { id:"video", name:"Video & Avatar", emoji:"🎬" },
  { id:"audio", name:"Voice & Audio", emoji:"🎙️" },
  { id:"code", name:"Code & Dev", emoji:"💻" },
  { id:"marketing", name:"Marketing & Ads", emoji:"📣" },
  { id:"productivity", name:"Productivity", emoji:"⚡" },
  { id:"business", name:"Business & Sales", emoji:"💼" },
  { id:"design", name:"Design & UI", emoji:"🖌️" },
  { id:"data", name:"Data & Research", emoji:"📊" },
  { id:"education", name:"Learning", emoji:"🎓" }
],
tools: [
  {id:"chatgpt",name:"ChatGPT",tagline:"The assistant that started it all — write, code, plan anything.",description:"OpenAI's conversational AI for writing, coding, brainstorming, data analysis and custom GPTs. The default baseline every other tool is compared against.",category:"chat",pricing:"Freemium",rating:4.9,votes:18432,url:"https://chat.openai.com",emoji:"🤖",grad:"linear-gradient(135deg,#10a37f,#0ea5e9)",tags:["chatbot","gpt-4","writing","coding"],featured:1,isNew:0,date:"2023-01-10"},
  {id:"midjourney",name:"Midjourney",tagline:"Stunning AI art from a Discord prompt.",description:"Text-to-image generator famous for cinematic, painterly, ultra-detailed visuals. V6 brings realistic hands, text rendering and style references.",category:"image",pricing:"Paid",rating:4.8,votes:15210,url:"https://midjourney.com",emoji:"⛵",grad:"linear-gradient(135deg,#6366f1,#a855f7)",tags:["art","illustration","discord"],featured:1,isNew:0,date:"2023-02-01"},
  {id:"runway",name:"Runway Gen-3",tagline:"Text-to-video studio for filmmakers.",description:"Generate and edit video from text, images or video. Inpainting, motion brush, green screen and 4K upscaling used by real film studios.",category:"video",pricing:"Freemium",rating:4.7,votes:9804,url:"https://runway.ml",emoji:"🎥",grad:"linear-gradient(135deg,#22d3ee,#6366f1)",tags:["video","editing","film"],featured:1,isNew:0,date:"2023-06-12"},
  {id:"elevenlabs",name:"ElevenLabs",tagline:"Most realistic AI voice cloning & TTS.",description:"Lifelike text-to-speech in 29 languages, instant voice cloning, dubbing and sound effects. The go-to for YouTube, podcasts and audiobooks.",category:"audio",pricing:"Freemium",rating:4.8,votes:12480,url:"https://elevenlabs.io",emoji:"🗣️",grad:"linear-gradient(135deg,#f472b6,#8b5cf6)",tags:["voice","tts","cloning","podcast"],featured:1,isNew:0,date:"2023-04-20"},
  {id:"cursor",name:"Cursor",tagline:"The AI-first code editor developers love.",description:"Fork of VS Code with codebase-wide chat, tab completion and agent mode that edits multiple files. Ships features 2x faster.",category:"code",pricing:"Freemium",rating:4.9,votes:13922,url:"https://cursor.sh",emoji:"⌨️",grad:"linear-gradient(135deg,#0ea5e9,#22c55e)",tags:["copilot","ide","agents"],featured:1,isNew:1,date:"2026-02-14"},
  {id:"notion-ai",name:"Notion AI",tagline:"Write, summarize & organize inside Notion.",description:"AI summaries, action items, translations and autofill databases right where your docs live. Best for teams already on Notion.",category:"productivity",pricing:"Paid",rating:4.6,votes:8730,url:"https://notion.so",emoji:"📝",grad:"linear-gradient(135deg,#e2e8f0,#64748b)",tags:["notes","wiki","summarizer"],featured:0,isNew:0,date:"2023-05-02"},
  {id:"jasper",name:"Jasper",tagline:"On-brand marketing copy in seconds.",description:"Marketing-focused writer with brand voice memory, 50+ templates, SEO mode and Surfer integration for blogs, ads and email.",category:"writing",pricing:"Paid",rating:4.5,votes:6214,url:"https://jasper.ai",emoji:"✨",grad:"linear-gradient(135deg,#f59e0b,#ef4444)",tags:["copywriting","blog","ads"],featured:0,isNew:0,date:"2023-01-22"},
  {id:"copy-ai",name:"Copy.ai",tagline:"Go-to-market workflows on autopilot.",description:"Prospecting, enrichment, outreach sequences and content repurposing powered by workflows, not just chat.",category:"marketing",pricing:"Free",rating:4.4,votes:5120,url:"https://copy.ai",emoji:"📋",grad:"linear-gradient(135deg,#8b5cf6,#ec4899)",tags:["sales","outreach","workflows"],featured:0,isNew:0,date:"2023-03-11"},
  {id:"synthesia",name:"Synthesia",tagline:"AI avatars that present your script.",description:"140+ avatars, 120 languages. Turn docs into training videos without cameras, actors or studios.",category:"video",pricing:"Paid",rating:4.6,votes:7430,url:"https://synthesia.io",emoji:"🧑‍💼",grad:"linear-gradient(135deg,#06b6d4,#3b82f6)",tags:["avatar","training","localization"],featured:0,isNew:0,date:"2023-02-18"},
  {id:"perplexity",name:"Perplexity",tagline:"Answer engine with live citations.",description:"Conversational search that reads the live web and cites sources. Pro adds GPT-4o, Claude and file analysis.",category:"data",pricing:"Freemium",rating:4.7,votes:11230,url:"https://perplexity.ai",emoji:"🔎",grad:"linear-gradient(135deg,#14b8a6,#3b82f6)",tags:["search","research","citations"],featured:1,isNew:0,date:"2023-07-01"},
  {id:"claude",name:"Claude",tagline:"Thoughtful long-context assistant by Anthropic.",description:"200K context, careful reasoning, artifacts for code/docs/design. Favorite of writers and analysts for nuanced work.",category:"chat",pricing:"Freemium",rating:4.8,votes:13150,url:"https://claude.ai",emoji:"🧠",grad:"linear-gradient(135deg,#f97316,#b45309)",tags:["assistant","analysis","long-context"],featured:1,isNew:0,date:"2023-08-10"},
  {id:"leonardo",name:"Leonardo AI",tagline:"Game assets & art with fine control.",description:"Models, canvas editor, texture generation and consistent characters. Free tier is generous for indie creators.",category:"image",pricing:"Freemium",rating:4.6,votes:6890,url:"https://leonardo.ai",emoji:"🦁",grad:"linear-gradient(135deg,#a855f7,#ec4899)",tags:["game","assets","art"],featured:0,isNew:0,date:"2023-09-05"},
  {id:"descript",name:"Descript",tagline:"Edit audio & video like a doc.",description:"Overdub voice cloning, filler-word removal, studio sound and screen recording. Podcasters' secret weapon.",category:"audio",pricing:"Freemium",rating:4.6,votes:5980,url:"https://descript.com",emoji:"🎧",grad:"linear-gradient(135deg,#0ea5e9,#6366f1)",tags:["podcast","editing","transcription"],featured:0,isNew:0,date:"2023-03-30"},
  {id:"github-copilot",name:"Muse",tagline:"Your AI pair programmer.",description:"Autocomplete and chat inside your IDE, trained on billions of lines. Huge time saver for boilerplate and tests.",category:"code",pricing:"Paid",rating:4.7,votes:10420,url:"https://github.com/features/copilot",emoji:"🐙",grad:"linear-gradient(135deg,#111827,#3b82f6)",tags:["autocomplete","ide","productivity"],featured:0,isNew:0,date:"2023-01-15"},
  {id:"canva-ai",name:"Canva Magic Studio",tagline:"Design anything with a prompt.",description:"Magic Write, Text-to-Image, Background remover and Beat Sync inside the world's easiest design tool.",category:"design",pricing:"Freemium",rating:4.5,votes:9340,url:"https://canva.com",emoji:"🪄",grad:"linear-gradient(135deg,#22d3ee,#a78bfa)",tags:["design","social","presentations"],featured:0,isNew:0,date:"2023-10-04"},
  {id:"pictory",name:"Pictory",tagline:"Blog post → faceless YouTube video.",description:"Auto script-to-video, captions, stock footage and voices. Built for creators pumping out shorts daily.",category:"video",pricing:"Paid",rating:4.4,votes:4210,url:"https://pictory.ai",emoji:"📹",grad:"linear-gradient(135deg,#f43f5e,#f59e0b)",tags:["youtube","shorts","captions"],featured:0,isNew:0,date:"2023-05-19"},
  {id:"surfer",name:"Surfer SEO",tagline:"Rank #1 with AI content optimization.",description:"Content score, NLP terms, internal linking and AI outline builder that reverse-engineers top-ranking pages.",category:"writing",pricing:"Paid",rating:4.5,votes:3870,url:"https://surferseo.com",emoji:"🏄",grad:"linear-gradient(135deg,#22c55e,#0ea5e9)",tags:["seo","blog","ranking"],featured:0,isNew:0,date:"2023-02-27"},
  {id:"hubspot-ai",name:"HubSpot Breeze",tagline:"AI CRM that sells while you sleep.",description:"Prospecting agent, content remix, predictive lead scoring and chatbots stitched into the HubSpot CRM.",category:"business",pricing:"Freemium",rating:4.4,votes:3560,url:"https://hubspot.com",emoji:"🧲",grad:"linear-gradient(135deg,#f97316,#ef4444)",tags:["crm","sales","email"],featured:0,isNew:1,date:"2026-01-20"},
  {id:"mem",name:"Mem",tagline:"Self-organizing notes with AI search.",description:"Capture fast, find instantly. Mem auto-tags and connects notes so you never organize again.",category:"productivity",pricing:"Freemium",rating:4.3,votes:2140,url:"https://mem.ai",emoji:"🧩",grad:"linear-gradient(135deg,#6366f1,#22d3ee)",tags:["notes","pkm","search"],featured:0,isNew:0,date:"2023-04-11"},
  {id:"duolingo-max",name:"Duolingo Max",tagline:"Learn languages with GPT-4 roleplay.",description:"Explain-my-answer and live roleplay conversations inside Duolingo lessons.",category:"education",pricing:"Paid",rating:4.5,votes:4890,url:"https://duolingo.com",emoji:"🦉",grad:"linear-gradient(135deg,#22c55e,#a3e635)",tags:["language","tutor"],featured:0,isNew:0,date:"2023-06-30"},
  {id:"tome",name:"Tome",tagline:"Storytelling slides from one sentence.",description:"Narrative decks with AI layouts, images and live embeds. Pitch decks in minutes.",category:"business",pricing:"Free",rating:4.3,votes:3120,url:"https://tome.app",emoji:"📖",grad:"linear-gradient(135deg,#ec4899,#8b5cf6)",tags:["slides","pitch","storytelling"],featured:0,isNew:0,date:"2023-03-08"},
  {id:"figma-ai",name:"Figma AI",tagline:"Design, rename & prototype with AI.",description:"First-draft UI, auto-rename layers, rewrite copy and make prototypes from prompts.",category:"design",pricing:"Freemium",rating:4.6,votes:7760,url:"https://figma.com",emoji:"🎛️",grad:"linear-gradient(135deg,#a855f7,#22d3ee)",tags:["ui","ux","prototype"],featured:0,isNew:1,date:"2026-03-02"},
  {id:"phind",name:"Phind",tagline:"Answer engine for developers.",description:"Code answers with live docs, repo context and VS Code extension. Like Perplexity but for code.",category:"code",pricing:"Free",rating:4.6,votes:5340,url:"https://phind.com",emoji:"🤿",grad:"linear-gradient(135deg,#0f172a,#22d3ee)",tags:["search","docs","debugging"],featured:0,isNew:0,date:"2023-08-22"},
  {id:"heygen",name:"HeyGen",tagline:"Spokesperson videos in 40 languages.",description:"URL-to-video, talking avatars and voice cloning for ads, onboarding and UGC at scale.",category:"video",pricing:"Freemium",rating:4.5,votes:6120,url:"https://heygen.com",emoji:"🎭",grad:"linear-gradient(135deg,#8b5cf6,#f59e0b)",tags:["avatar","ads","ugc"],featured:1,isNew:1,date:"2026-02-01"},
  {id:"gamma",name:"Gamma",tagline:"Docs, decks & sites that design themselves.",description:"Prompt → polished cards with images, charts and embeds you can publish as a site.",category:"productivity",pricing:"Freemium",rating:4.6,votes:6980,url:"https://gamma.app",emoji:"🃏",grad:"linear-gradient(135deg,#f472b6,#6366f1)",tags:["slides","docs","website"],featured:0,isNew:1,date:"2026-01-11"},
  {id:"writesonic",name:"Writesonic",tagline:"SEO articles & chatbots for brands.",description:"AI Article Writer 6.0, Botsonic chatbots and Photosonic images in one subscription.",category:"writing",pricing:"Free",rating:4.3,votes:4450,url:"https://writesonic.com",emoji:"⌨️",grad:"linear-gradient(135deg,#3b82f6,#8b5cf6)",tags:["blog","chatbot","seo"],featured:0,isNew:0,date:"2023-02-14"},
  {id:"beautiful-ai",name:"Beautiful.ai",tagline:"Investor-ready decks automatically.",description:"Smart templates that keep every slide on-brand while you type.",category:"business",pricing:"Paid",rating:4.2,votes:1890,url:"https://beautiful.ai",emoji:"💎",grad:"linear-gradient(135deg,#0ea5e9,#a855f7)",tags:["pitch","slides"],featured:0,isNew:0,date:"2023-05-25"},
  {id:"elicit",name:"Elicit",tagline:"Research papers, summarized in seconds.",description:"Find papers, extract claims, build literature reviews. Loved by PhDs and analysts.",category:"data",pricing:"Free",rating:4.6,votes:3980,url:"https://elicit.com",emoji:"📚",grad:"linear-gradient(135deg,#14b8a6,#84cc16)",tags:["papers","literature-review"],featured:0,isNew:0,date:"2023-07-19"}
]
};
